### PR TITLE
Ha tool regions

### PR DESCRIPTION
**Pull request by jsuchome**
This is actually a copy of @aspiers 's PR to upstream repo: https://github.com/madkiss/openstack-resource-agents/pull/21

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by aspiers** [comment]
I was thinking it would be better to have this in a dedicated branch - one per non-upstreamed topic, and then merge them all into a rebase-able branch which gets used for packaging.

**Comment by jsuchome** [comment]
Hm, but I think we'd like to use this repo for a service that would create the tarball for our package. Would we need to add each such new branch into the service definition?

**Comment by aspiers** [comment]
No, just the merged branch.

**Comment by jsuchome** [comment]
https://github.com/SUSE-Cloud/openstack-resource-agents/pull/2

**Pull request closed without merging**
